export const toolErrorCodes = {
  aborted: "tool.aborted",
  conversionFailed: "webfetch.conversion-failed",
  disabled: "tool.disabled",
  executionFailed: "tool.execution-failed",
  fetchFailed: "webfetch.fetch-failed",
  httpError: "webfetch.http-error",
  invalidContext: "tool.invalid-context",
  invalidDefinition: "tool.invalid-definition",
  invalidInput: "tool.invalid-input",
  invalidName: "tool.invalid-name",
  invalidOutput: "tool.invalid-output",
  invalidUrl: "webfetch.invalid-url",
  outputLimit: "tool.output-limit",
  registrationConflict: "tool.registration-conflict",
  responseTooLarge: "webfetch.response-too-large",
  timeout: "tool.timeout",
  unknown: "tool.unknown",
  unsupportedContentType: "webfetch.unsupported-content-type",
} as const
