import { urlSimulateScenario } from "../ui/simulate_url/urlSimulate.js"

export const simulationScenarioSessionMetadata = {
  "compaction-summary": {
    href: urlSimulateScenario("compaction-summary"),
    label: "Compaction summary",
    model: "simulation-compaction-summary",
    agentId: "example-agent-simulation-compaction-summary",
    sessionId: "example-session-simulation-compaction-summary",
    agentConfiguration: {
      compaction: {
        auto: true,
        enabled: true,
        maxOverflowRetries: 1,
        maxSummaryTokens: 128,
        pressureThreshold: 0.8,
        recentTokenBudget: 4_096,
        reserveOutputTokens: 512,
      },
      generation: { maxTokens: 128 },
    },
  },
  streaming: {
    href: urlSimulateScenario("streaming"),
    label: "Streaming",
    model: "simulation-streaming",
    agentId: "example-agent-simulation-streaming",
    sessionId: "example-session-simulation-streaming",
  },
  "thinking-tools": {
    href: urlSimulateScenario("thinking-tools"),
    label: "Thinking and tools",
    model: "simulation-thinking-tools",
    agentId: "example-agent-simulation-thinking-tools",
    sessionId: "example-session-simulation-thinking-tools",
  },
  "retry-success": {
    href: urlSimulateScenario("retry-success"),
    label: "Retry success",
    model: "simulation-retry-success",
    agentId: "example-agent-simulation-retry-success",
    sessionId: "example-session-simulation-retry-success",
  },
  "retry-exhausted": {
    href: urlSimulateScenario("retry-exhausted"),
    label: "Retry exhausted",
    model: "simulation-retry-exhausted",
    agentId: "example-agent-simulation-retry-exhausted",
    sessionId: "example-session-simulation-retry-exhausted",
  },
  "terminal-error": {
    href: urlSimulateScenario("terminal-error"),
    label: "Terminal error",
    model: "simulation-terminal-error",
    agentId: "example-agent-simulation-terminal-error",
    sessionId: "example-session-simulation-terminal-error",
  },
  "unexpected-end": {
    href: urlSimulateScenario("unexpected-end"),
    label: "Unexpected end",
    model: "simulation-unexpected-end",
    agentId: "example-agent-simulation-unexpected-end",
    sessionId: "example-session-simulation-unexpected-end",
  },
  "detached-reload": {
    href: urlSimulateScenario("detached-reload"),
    label: "Detached run reload",
    model: "simulation-detached-reload",
    agentId: "example-agent-simulation-detached-reload",
    sessionId: "example-session-simulation-detached-reload",
  },
  "retry-reload": {
    href: urlSimulateScenario("retry-reload"),
    label: "Retry across reload",
    model: "simulation-retry-reload",
    agentId: "example-agent-simulation-retry-reload",
    sessionId: "example-session-simulation-retry-reload",
  },
  "tool-activity-reload": {
    href: urlSimulateScenario("tool-activity-reload"),
    label: "Tool activity across reload",
    model: "simulation-tool-activity-reload",
    agentId: "example-agent-simulation-tool-activity-reload",
    sessionId: "example-session-simulation-tool-activity-reload",
  },
  cancellation: {
    href: urlSimulateScenario("cancellation"),
    label: "Cancellation",
    model: "simulation-cancellation",
    agentId: "example-agent-simulation-cancellation",
    sessionId: "example-session-simulation-cancellation",
  },
} as const
