import type { DemoScenario } from "./demoScenario.js"
import type { DemoScenarioFixture } from "./demoScenarioFixture.js"
import { demoSurfaceFixtures } from "./demoSurfaceFixtures.js"
import { demoWorkspaceFixtures } from "./demoWorkspaceFixtures.js"

const fileScenarioFixture = {
  activeFile: "DemoShell.tsx",
  activeSession: "Review project files",
  eyebrow: "File workspace · deterministic fixture",
  files: [],
  heading: "Review project files",
  messages: [
    {
      author: "user",
      body: "Inspect the changed files, preview the documentation, and mention the exact source lines that need review.",
      detail: "11:28",
      kind: "markdown",
    },
    {
      author: "assistant",
      body: "The project workspace is open with local fixture content. No filesystem or network calls are made.",
      detail: "fixture ready",
      kind: "markdown",
    },
  ],
  composer: {
    action: "Send",
    placeholder: "Use @ to add file context...",
    status: "selected files remain local to this demo",
  },
  sessions: [
    { active: true, label: "Review project files", meta: "now" },
    { branch: true, label: "Compare workspace diff", meta: "6m" },
    { label: "Preview architecture docs", meta: "21m" },
  ],
} as const satisfies DemoScenarioFixture

const surfaceScenarioFixture = {
  activeFile: null,
  activeSession: "Configuration review",
  eyebrow: "Local settings · deterministic fixture",
  files: [],
  heading: "Configuration review",
  messages: [
    {
      author: "assistant",
      body: "This showcase is assembled from local fixture data and does not load providers, plugins, or project configuration.",
      detail: "display only",
      kind: "markdown",
    },
  ],
  composer: {
    action: "Send",
    placeholder: "Configuration scenarios are read-only...",
    status: "fixture state · no runtime integration",
  },
  sessions: [
    { active: true, label: "Configuration review", meta: "now" },
    { label: "Inspect local preferences", meta: "8m" },
    { label: "Review session context", meta: "22m" },
  ],
} as const satisfies DemoScenarioFixture

export const demoScenarioFixtures = {
  welcome: {
    activeFile: null,
    activeSession: null,
    eyebrow: "Deterministic UI showcase",
    files: [
      { depth: 0, kind: "directory", label: "src" },
      { depth: 1, kind: "file", label: "main.tsx" },
      { depth: 0, kind: "file", label: "README.md" },
    ],
    heading: "Start a focused coding session",
    messages: [],
    composer: {
      action: "Send",
      placeholder: "Describe the change you want to make...",
      status: "New session · Enter to send · Shift+Enter for a new line",
    },
    sessions: [{ label: "No session selected", meta: "Choose a scenario above" }],
  },
  conversation: {
    activeFile: "DemoMessage.tsx",
    activeSession: "Polish message rendering",
    eyebrow: "Today · deterministic transcript",
    files: [
      { depth: 0, kind: "directory", label: "src" },
      { depth: 1, kind: "directory", label: "ui" },
      { depth: 2, kind: "directory", label: "demo" },
      { depth: 3, kind: "file", label: "DemoMessage.tsx", status: "added" },
      { depth: 3, kind: "file", label: "demoScenarioFixtures.ts", status: "modified" },
    ],
    heading: "Polish message rendering",
    messages: [
      {
        actions: ["Copy", "Edit", "Fork"],
        author: "user",
        body: "Please add **deterministic chat states** and keep the demo isolated from production code. Use `Show` for optional regions.",
        detail: "10:42",
        kind: "markdown",
      },
      {
        actions: ["Copy"],
        author: "assistant",
        body: "I’ll inspect the typed registry first, then model each visual state as local fixture data.",
        detail: "Thought for 8s",
        kind: "thinking",
        label: "Reasoning",
      },
      {
        author: "assistant",
        body: '{ "path": "src/ui/demo/DemoShell.tsx", "offset": 76, "limit": 80 }',
        detail: "0.2s",
        kind: "tool",
        label: "read",
        result: '76: <section aria-label="Conversation">\n77:   <div class="flex items-center...">',
        resultTone: "success",
      },
      {
        author: "assistant",
        body: '{ "path": "src/ui/demo/Missing.tsx" }',
        detail: "0.1s",
        kind: "tool",
        label: "read",
        result: "ENOENT: no such file or directory",
        resultTone: "error",
      },
      {
        actions: ["Copy"],
        author: "assistant",
        body: "export function DemoMessage(props: DemoMessageProps) {\n  return <article data-kind={props.message.kind} />\n}",
        detail: "TypeScript · 4 lines",
        kind: "code",
        label: "DemoMessage.tsx",
      },
      {
        author: "user",
        body: "chat-reference.png",
        detail: "PNG · 1440 × 900 · 284 KB",
        kind: "attachment",
        label: "UI reference",
      },
      {
        actions: ["Copy", "Retry"],
        author: "assistant",
        body: "Provider stopped before the final content block was complete.",
        detail: "request_01J8DEMO",
        kind: "error",
        label: "Generation error",
      },
      {
        actions: ["Copy"],
        author: "assistant",
        body: "### Implemented\n\n- Added typed message variants\n- Kept fixtures local and deterministic\n- Preserved the responsive three-region shell",
        detail: "1,248 tokens · 24.6 t/s · 10:43",
        kind: "markdown",
      },
    ],
    composer: {
      action: "Send",
      placeholder: "Ask a follow-up...",
      status: "deterministic · standard tools · high thinking",
    },
    sessions: [
      { active: true, label: "Polish message rendering", meta: "now" },
      { branch: true, label: "Try compact tool cards", meta: "4m" },
      { label: "Review Markdown rhythm", meta: "18m" },
    ],
  },
  streaming: {
    activeFile: "DemoShell.tsx",
    activeSession: "Verify responsive states",
    eyebrow: "Live fixture · sequence 184",
    files: [
      { depth: 0, kind: "directory", label: "src" },
      { depth: 1, kind: "directory", label: "ui" },
      { depth: 2, kind: "directory", label: "demo" },
      { depth: 3, kind: "file", label: "DemoShell.tsx", status: "modified" },
    ],
    heading: "Verify responsive states",
    messages: [
      {
        actions: ["Copy", "Edit"],
        author: "user",
        body: "Check the scenario navigation at desktop and mobile widths, then report any overflow.",
        detail: "11:06",
        kind: "markdown",
      },
      {
        author: "assistant",
        body: '{ "viewport": "390x844", "path": "/demo/streaming" }',
        kind: "tool",
        label: "browser snapshot",
        result: "Running accessibility and overflow checks...",
        resultTone: "success",
      },
      {
        author: "assistant",
        body: "The shell reflows to one column. I’m checking the composer queue and horizontal scenario navigation next",
        detail: "312 tokens · 18.4 t/s",
        kind: "markdown",
        streaming: true,
      },
    ],
    composer: {
      action: "Abort",
      placeholder: "Steer the current response or queue a follow-up...",
      queued: [
        { kind: "steer", text: "Also check that tool errors remain readable." },
        { kind: "follow-up", text: "Summarize desktop and mobile results." },
      ],
      retry: "Retrying stream · attempt 2 of 3 · previous connection ended early",
      status: "Streaming · Esc to abort · Enter queues as steer",
    },
    sessions: [
      { active: true, label: "Verify responsive states", meta: "running", running: true },
      { label: "Recover interrupted stream", meta: "8m" },
      { label: "Queue follow-up prompt", meta: "15m" },
    ],
  },
  "long-chat": {
    activeFile: "DemoShell.tsx",
    activeSession: "Architecture review",
    eyebrow: "48 messages · compacted once",
    files: [
      { depth: 0, kind: "directory", label: "src" },
      { depth: 1, kind: "directory", label: "ui" },
      { depth: 2, kind: "directory", label: "demo" },
      { depth: 3, kind: "file", label: "DemoShell.tsx", status: "modified" },
    ],
    heading: "Architecture review",
    history: { hiddenCount: 32, label: "Load 32 earlier messages" },
    messages: [
      { author: "user", body: "Start by inventorying the existing route boundary.", detail: "09:12", kind: "markdown" },
      {
        author: "assistant",
        body: "The `/demo` branch occurs before Zero mounts, so fixtures remain client-only.",
        detail: "09:13",
        kind: "markdown",
      },
      {
        author: "user",
        body: "Define the scenario contract without widening shared domain types.",
        detail: "09:24",
        kind: "markdown",
      },
      {
        author: "assistant",
        body: "The contract stays under `src/ui/demo/` and uses discriminated visual variants.",
        detail: "09:26",
        kind: "markdown",
      },
      { author: "user", body: "How should long conversations remain navigable?", detail: "09:48", kind: "markdown" },
      {
        author: "assistant",
        body: "Use lazy history at the top and a turn minimap on desktop, with concise labels for quick orientation.",
        detail: "09:51",
        kind: "markdown",
      },
      {
        author: "user",
        body: "Keep the mobile transcript full width and remove the minimap rail.",
        detail: "10:04",
        kind: "markdown",
      },
      {
        actions: ["Copy"],
        author: "assistant",
        body: "The responsive shell now hides the rail below 720px while retaining the earlier-history affordance.",
        detail: "10:06",
        kind: "markdown",
      },
    ],
    minimap: [
      { label: "Route boundary" },
      { label: "Fixture contract" },
      { label: "Message variants" },
      { label: "Tool results" },
      { active: true, label: "Long chat navigation" },
      { label: "Responsive review" },
      { label: "Verification" },
    ],
    composer: {
      action: "Send",
      placeholder: "Continue the architecture review...",
      status: "48 messages · 18.2k / 32k context · history available",
    },
    sessions: [
      { active: true, label: "Architecture review", meta: "now" },
      { branch: true, label: "Alternative minimap", meta: "22m" },
      { label: "Earlier shell inventory", meta: "2h" },
    ],
  },
  workspace: {
    activeFile: "DemoShell.tsx",
    activeSession: "Build the demo shell",
    eyebrow: "Local / codeline / main",
    files: [
      { depth: 0, kind: "directory", label: "src" },
      { depth: 1, kind: "directory", label: "ui" },
      { depth: 2, kind: "directory", label: "demo" },
      { depth: 3, kind: "file", label: "DemoShell.tsx", status: "modified" },
      { depth: 3, kind: "file", label: "demoScenarioFixtures.ts", status: "added" },
      { depth: 0, kind: "file", label: "package.json" },
    ],
    heading: "Build the demo shell",
    messages: [
      {
        author: "user",
        body: "Create an isolated /demo foundation with deterministic fixtures and no backend dependencies.",
        detail: "10:42",
      },
      {
        author: "assistant",
        body: "The route now branches before Zero mounts. The demo is composed from local typed fixtures and keeps the production workspace untouched.",
        detail: "2 files changed · verified locally",
      },
    ],
    composer: {
      action: "Send",
      placeholder: "Ask Codeline to make a change...",
      status: "deterministic · standard tools",
    },
    sessions: [
      { active: true, label: "Build the demo shell", meta: "now" },
      { branch: true, label: "Explore compact navigation", meta: "12m" },
      { label: "Review responsive layout", meta: "1h" },
      { label: "Plan file preview states", meta: "yesterday", running: true },
    ],
  },
  files: { ...fileScenarioFixture, workspace: demoWorkspaceFixtures.files },
  markdown: { ...fileScenarioFixture, activeFile: "workspace-guide.md", workspace: demoWorkspaceFixtures.markdown },
  mermaid: { ...fileScenarioFixture, activeFile: "sync-flow.mmd", workspace: demoWorkspaceFixtures.mermaid },
  diff: { ...fileScenarioFixture, activeFile: "README.md", workspace: demoWorkspaceFixtures.diff },
  models: { ...surfaceScenarioFixture, heading: "Model configuration", surface: demoSurfaceFixtures.models },
  skills: { ...surfaceScenarioFixture, heading: "Skill configuration", surface: demoSurfaceFixtures.skills },
  stats: { ...surfaceScenarioFixture, heading: "Session statistics", surface: demoSurfaceFixtures.stats },
  "system-prompt": {
    ...surfaceScenarioFixture,
    heading: "System prompt preview",
    surface: demoSurfaceFixtures["system-prompt"],
  },
  extensions: { ...surfaceScenarioFixture, heading: "Extension status", surface: demoSurfaceFixtures.extensions },
  "written-files": {
    ...surfaceScenarioFixture,
    heading: "Turn written files",
    surface: demoSurfaceFixtures["written-files"],
  },
} as const satisfies Record<DemoScenario["slug"], DemoScenarioFixture>
