import type { DemoWorkspaceFixture } from "./demoWorkspaceFixture.js"

const workspaceTree = [
  { depth: 0, id: "src", kind: "directory", label: "src" },
  { depth: 1, id: "src-ui", kind: "directory", label: "ui", parentId: "src" },
  {
    depth: 2,
    id: "demo-shell",
    kind: "file",
    label: "DemoShell.tsx",
    parentId: "src-ui",
    status: "modified",
    tabId: "source",
  },
  { depth: 0, id: "docs", kind: "directory", label: "docs" },
  {
    depth: 1,
    id: "guide",
    kind: "file",
    label: "workspace-guide.md",
    parentId: "docs",
    status: "added",
    tabId: "markdown",
  },
  {
    depth: 1,
    id: "flow",
    kind: "file",
    label: "sync-flow.mmd",
    parentId: "docs",
    status: "untracked",
    tabId: "mermaid",
  },
  { depth: 0, id: "readme", kind: "file", label: "README.md", status: "conflict", tabId: "diff" },
  { depth: 0, id: "reference", kind: "file", label: "reference.png", status: "uploaded" },
] as const

const workspaceTabs = [
  {
    diff: {
      left: [
        { kind: "same", number: 1, text: "export function DemoShell() {" },
        { kind: "removed", number: 2, text: '  return <main class="workspace">' },
        { kind: "removed", number: 3, text: "    <LegacyFiles />" },
        { kind: "same", number: 4, text: "  </main>" },
      ],
      right: [
        { kind: "same", number: 1, text: "export function DemoShell() {" },
        { kind: "added", number: 2, text: '  return <main class="workspace-grid">' },
        { kind: "added", number: 3, text: "    <DemoWorkspacePanel />" },
        { kind: "same", number: 4, text: "  </main>" },
      ],
    },
    id: "source",
    kind: "source",
    label: "DemoShell.tsx",
    language: "TypeScript JSX",
    path: "src/ui/demo/DemoShell.tsx",
    source: [
      'import { DemoWorkspacePanel } from "./DemoWorkspacePanel.js"',
      "",
      "export function DemoShell() {",
      '  return <main class="workspace-grid">',
      "    <DemoWorkspacePanel />",
      "  </main>",
      "}",
    ],
    status: "modified",
  },
  {
    frontmatter: [
      { key: "title", value: "Workspace guide" },
      { key: "status", value: "review" },
      { key: "owners", value: "ui-platform" },
    ],
    id: "markdown",
    kind: "markdown",
    label: "workspace-guide.md",
    language: "Markdown",
    markdown: [
      { heading: "File workspace", text: "Inspect local project context without leaving the active conversation." },
      {
        heading: "Review flow",
        text: "Select source lines, compare changes, then insert a precise @mention into chat.",
      },
      { text: "All content in this showcase is deterministic fixture data." },
    ],
    path: "docs/workspace-guide.md",
    source: [
      "---",
      "title: Workspace guide",
      "status: review",
      "owners: ui-platform",
      "---",
      "",
      "# File workspace",
      "",
      "Inspect local project context without leaving the active conversation.",
      "",
      "## Review flow",
      "",
      "Select source lines, compare changes, then insert a precise @mention into chat.",
    ],
    status: "added",
  },
  {
    id: "mermaid",
    kind: "mermaid",
    label: "sync-flow.mmd",
    language: "Mermaid",
    mermaid: {
      edges: [
        { from: "Tree", to: "Tabs" },
        { from: "Tabs", to: "Viewer" },
        { from: "Viewer", to: "Chat mention" },
      ],
      nodes: [
        { id: "Tree", label: "Project tree", tone: "neutral" },
        { id: "Tabs", label: "Open tabs", tone: "accent" },
        { id: "Viewer", label: "Preview / diff", tone: "success" },
        { id: "Chat mention", label: "@ precise context", tone: "accent" },
      ],
    },
    path: "docs/sync-flow.mmd",
    source: ["flowchart LR", "  Tree --> Tabs", "  Tabs --> Viewer", "  Viewer --> Mention[Chat mention]"],
    status: "untracked",
  },
  {
    diff: {
      left: [
        { kind: "same", number: 12, text: "## Development" },
        { kind: "removed", number: 13, text: "Run the UI with bun run dev:ui." },
        { kind: "removed", number: 14, text: "Changes are loaded from disk." },
        { kind: "same", number: 15, text: "Keep fixtures deterministic." },
      ],
      right: [
        { kind: "same", number: 12, text: "## Development" },
        { kind: "added", number: 13, text: "Use repository-managed development services." },
        { kind: "added", number: 14, text: "Demo files are fixture-only and client-side." },
        { kind: "same", number: 15, text: "Keep fixtures deterministic." },
      ],
    },
    id: "diff",
    kind: "markdown",
    label: "README.md",
    language: "Markdown",
    path: "README.md",
    source: [
      "## Development",
      "",
      "Use repository-managed development services.",
      "Demo files are fixture-only and client-side.",
      "",
      "Keep fixtures deterministic.",
    ],
    status: "conflict",
  },
] as const

export const demoWorkspaceFixtures = {
  files: {
    activeTabId: "source",
    initialMode: "source",
    notice: "4 changes · +18 −7 · local fixture",
    tree: workspaceTree,
    tabs: workspaceTabs,
    uploadConflict: "reference.png already exists",
  },
  markdown: {
    activeTabId: "markdown",
    initialMode: "preview",
    notice: "Frontmatter parsed · preview ready",
    tree: workspaceTree,
    tabs: workspaceTabs,
    uploadConflict: "workspace-guide.md already exists",
  },
  mermaid: {
    activeTabId: "mermaid",
    initialMode: "preview",
    notice: "Diagram preview · 4 nodes · 3 edges",
    tree: workspaceTree,
    tabs: workspaceTabs,
    uploadConflict: "sync-flow.mmd already exists",
  },
  diff: {
    activeTabId: "diff",
    initialMode: "diff",
    notice: "Conflict · compare working tree with HEAD",
    tree: workspaceTree,
    tabs: workspaceTabs,
    uploadConflict: "README.md already exists",
  },
} as const satisfies Record<"diff" | "files" | "markdown" | "mermaid", DemoWorkspaceFixture>
