import type { DemoSpecimen } from "./demoSpecimen.js"

export const demoComponentSpecimenRegistry = [
  {
    description: "Branch tree, search, selection, loading, empty, and error states.",
    href: "/demo/components/session-list",
    label: "Session list",
    slug: "session-list",
    variants: ["ready", "streaming", "loading", "empty", "error"],
  },
  {
    description: "Conversation header, rename control, finalized messages, and composer.",
    href: "/demo/components/selected-session",
    label: "Selected session",
    slug: "selected-session",
    variants: ["ready", "streaming", "loading", "empty", "error"],
  },
  {
    description: "Composer with in-flight messages, streaming status, and error reporting.",
    href: "/demo/components/session-chat",
    label: "Session chat",
    slug: "session-chat",
    variants: ["ready", "streaming", "error"],
  },
  {
    description: "Server and agent selection with loading, empty, and error outcomes.",
    href: "/demo/components/session-target-selector",
    label: "Session target selector",
    slug: "session-target-selector",
    variants: ["ready", "loading", "empty", "error"],
  },
  {
    description: "Provider model selection across idle, loading, ready, and error states.",
    href: "/demo/components/provider-model-selector",
    label: "Provider model selector",
    slug: "provider-model-selector",
    variants: ["ready", "loading", "empty", "error"],
  },
  {
    description: "Directory listing, open file tabs, and markdown, image, loading, empty, and error previews.",
    href: "/demo/components/project-browser",
    label: "Project browser",
    slug: "project-browser",
    variants: ["ready", "editing", "loading", "empty", "error"],
  },
  {
    description: "Working tree changes, local branches, rename form, and unavailable repository states.",
    href: "/demo/components/project-git-panel",
    label: "Project Git panel",
    slug: "project-git-panel",
    variants: ["ready", "streaming", "editing", "loading", "empty", "error"],
  },
  {
    description: "Markdown editor and preview across split, edit-only, and empty content.",
    href: "/demo/components/note-content-field",
    label: "Note content field",
    slug: "note-content-field",
    variants: ["ready", "editing", "empty"],
  },
  {
    description: "Edit, preview, and split view mode selection.",
    href: "/demo/components/note-view-mode-switcher",
    label: "Note view mode switcher",
    slug: "note-view-mode-switcher",
    variants: ["ready", "editing"],
  },
  {
    description: "Back navigation from a note detail screen to the notes index.",
    href: "/demo/components/note-back-link",
    label: "Note back link",
    slug: "note-back-link",
    variants: ["ready"],
  },
  {
    description: "Inline session title editing with validation, saving, and cancel.",
    href: "/demo/components/session-rename-control",
    label: "Session rename control",
    slug: "session-rename-control",
    variants: ["ready"],
  },
  {
    description: "Finalized user and assistant messages with rendered Markdown and copy feedback.",
    href: "/demo/components/finalized-message",
    label: "Finalized message",
    slug: "finalized-message",
    variants: ["ready", "editing", "empty"],
  },
  {
    description: "Light, dark, and system theme cycling.",
    href: "/demo/components/theme-switcher",
    label: "Theme switcher",
    slug: "theme-switcher",
    variants: ["ready"],
  },
  {
    description: "Combined app, event-feed, and API connection icon with a details popover.",
    href: "/demo/components/connection-status-indicator",
    label: "Connection status indicator",
    slug: "connection-status-indicator",
    variants: ["ready", "loading", "empty", "streaming", "error"],
  },
] as const satisfies readonly DemoSpecimen[]
